language: python
python: 3.6
install: pip install -r requirements.txt
script: python manage.py test
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: cs50w-final
  run: 
    - python manage.py migrate
    - heroku ps:scale web=1
  on: master
